import type {
  Account,
  CaseRecord,
  Doctor,
  Hospital,
  PatientProfile,
} from "./types";

/**
 * Demo data for the AyuSetu prototype.
 * Replace this module with real Lovable Cloud queries later — the shapes
 * mirror the intended database tables.
 */

export const hospitals: Hospital[] = [
  {
    id: "h1",
    name: "Sunrise Multispeciality Hospital",
    city: "Hyderabad",
    address: "Plot 14, Jubilee Hills, Hyderabad, Telangana",
    phone: "+91 40 4455 1200",
    emergencyPhone: "+91 40 4455 1999",
    departments: [
      "General Medicine",
      "Pediatrics",
      "Cardiology",
      "Orthopaedics",
      "Dermatology",
    ],
  },
  {
    id: "h2",
    name: "Ashwini Care Hospital",
    city: "Vijayawada",
    address: "MG Road, Governorpet, Vijayawada, Andhra Pradesh",
    phone: "+91 866 233 8800",
    emergencyPhone: "+91 866 233 8899",
    departments: ["General Medicine", "ENT", "Gynaecology", "Pulmonology"],
  },
  {
    id: "h3",
    name: "Lotus Community Health Centre",
    city: "Warangal",
    address: "Hanamkonda Main Road, Warangal, Telangana",
    phone: "+91 870 244 7711",
    emergencyPhone: "+91 870 244 7700",
    departments: ["General Medicine", "Pediatrics", "Orthopaedics"],
  },
];

export const doctors: Doctor[] = [
  {
    id: "d1",
    name: "Dr. Ravi Kumar",
    hospitalId: "h1",
    department: "General Medicine",
    qualification: "MBBS, MD (General Medicine)",
    experienceYears: 14,
    available: true,
  },
  {
    id: "d2",
    name: "Dr. Sneha Reddy",
    hospitalId: "h1",
    department: "Pediatrics",
    qualification: "MBBS, DCH",
    experienceYears: 9,
    available: true,
  },
  {
    id: "d3",
    name: "Dr. Arun Menon",
    hospitalId: "h1",
    department: "Cardiology",
    qualification: "MBBS, DM (Cardiology)",
    experienceYears: 18,
    available: false,
  },
  {
    id: "d4",
    name: "Dr. Priya Nair",
    hospitalId: "h2",
    department: "General Medicine",
    qualification: "MBBS, MD",
    experienceYears: 11,
    available: true,
  },
  {
    id: "d5",
    name: "Dr. Imran Sheikh",
    hospitalId: "h2",
    department: "Pulmonology",
    qualification: "MBBS, MD (Pulmonary Medicine)",
    experienceYears: 7,
    available: true,
  },
  {
    id: "d6",
    name: "Dr. Lakshmi Prasad",
    hospitalId: "h3",
    department: "General Medicine",
    qualification: "MBBS",
    experienceYears: 5,
    available: true,
  },
];

export const accounts: Account[] = [
  {
    id: "a1",
    email: "namyatha@demo.in",
    name: "Namyatha Pulivarthi",
    role: "patient",
  },
  { id: "a2", email: "aarav@demo.in", name: "Aarav Sharma", role: "patient" },
  {
    id: "a3",
    email: "ravi@demo.in",
    name: "Dr. Ravi Kumar",
    role: "doctor",
    doctorId: "d1",
    hospitalId: "h1",
  },
  {
    id: "a4",
    email: "priya@demo.in",
    name: "Dr. Priya Nair",
    role: "doctor",
    doctorId: "d4",
    hospitalId: "h2",
  },
  {
    id: "a5",
    email: "admin@sunrise.in",
    name: "Sunrise Administration",
    role: "management",
    hospitalId: "h1",
  },
];

export const profiles: PatientProfile[] = [
  {
    id: "p1",
    patientId: "PT-10234",
    ownerAccountId: "a1",
    name: "Namyatha Pulivarthi",
    relation: "Self",
    dob: "2005-04-18",
    gender: "Female",
    phone: "+91 98490 12345",
    email: "namyatha@demo.in",
    bloodGroup: "O+",
    allergies: "Dust",
    medications: "None",
    conditions: "None",
    hospitalId: "h1",
    preferredDoctorId: "d1",
  },
  {
    id: "p2",
    patientId: "PT-10891",
    ownerAccountId: "a1",
    name: "Venkat Rao (Grandfather)",
    relation: "Grandfather",
    dob: "1948-11-02",
    gender: "Male",
    phone: "+91 98490 12345",
    bloodGroup: "B+",
    allergies: "Penicillin",
    medications: "Metformin 500mg twice daily",
    conditions: "Type 2 Diabetes, Hypertension",
    hospitalId: "h1",
    preferredDoctorId: "d1",
  },
  {
    id: "p3",
    patientId: "PT-11002",
    ownerAccountId: "a2",
    name: "Aarav Sharma",
    relation: "Self",
    dob: "1991-01-27",
    gender: "Male",
    phone: "+91 90000 55221",
    bloodGroup: "A+",
    allergies: "Not provided",
    medications: "Not provided",
    conditions: "None",
    hospitalId: "h2",
    preferredDoctorId: "d4",
  },
  {
    id: "p4",
    patientId: "PT-11318",
    ownerAccountId: "a2",
    name: "Ira Sharma (Daughter)",
    relation: "Daughter",
    dob: "2019-08-09",
    gender: "Female",
    phone: "+91 90000 55221",
    bloodGroup: "A+",
    allergies: "None known",
    medications: "None",
    conditions: "None",
    hospitalId: "h1",
    preferredDoctorId: "d2",
  },
];

export const cases: CaseRecord[] = [
  {
    id: "c1",
    caseId: "CS-2026-0041",
    profileId: "p1",
    hospitalId: "h1",
    doctorId: "d1",
    type: "new",
    status: "completed",
    language: "en",
    createdAt: "2026-06-12T09:20:00.000Z",
    reviewedAt: "2026-06-12T11:00:00.000Z",
    chiefComplaint: "Dry cough",
    duration: "5 days",
    symptoms: "Dry cough, mild throat irritation, disturbed sleep at night",
    severity: "Mild",
    pastHistory: "No major illnesses",
    allergies: "Dust",
    medications: "None",
    familyHistory: "Father has asthma",
    other: "Cough worsens in the evening",
    aiSummary:
      "21-year-old patient presenting with dry cough for five days with mild throat irritation and disturbed sleep. Known dust allergy. Family history of asthma.",
    notes: [
      {
        id: "n1",
        author: "Dr. Ravi Kumar",
        text: "Examined in OPD. Advised steam inhalation and review after one week.",
        createdAt: "2026-06-12T11:05:00.000Z",
        kind: "note",
      },
    ],
  },
  {
    id: "c2",
    caseId: "CS-2026-0113",
    profileId: "p1",
    hospitalId: "h1",
    doctorId: "d1",
    type: "new",
    status: "submitted",
    language: "en",
    createdAt: "2026-09-04T07:10:00.000Z",
    chiefComplaint: "Fever",
    duration: "3 days",
    symptoms: "Fever, body pain, headache, reduced appetite",
    severity: "Moderate",
    pastHistory: "Cough episode in June 2026",
    allergies: "Dust",
    medications: "Paracetamol taken twice",
    familyHistory: "Father has asthma",
    other: "No vomiting reported",
    aiSummary:
      "21-year-old patient presenting with fever for three days associated with body pain and headache. Reduced appetite. No vomiting reported.",
    notes: [],
  },
  {
    id: "c3",
    caseId: "CS-2026-0115",
    profileId: "p2",
    hospitalId: "h1",
    doctorId: "d1",
    type: "follow-up",
    status: "reviewed",
    language: "te",
    createdAt: "2026-09-05T05:40:00.000Z",
    reviewedAt: "2026-09-05T08:15:00.000Z",
    parentCaseId: "c1",
    chiefComplaint: "Follow-up: knee pain and blood sugar control",
    duration: "Since last visit (2 weeks)",
    symptoms: "Knee pain reduced, occasional giddiness in the morning",
    severity: "Mild",
    pastHistory: "Type 2 Diabetes, Hypertension",
    allergies: "Penicillin",
    medications: "Metformin 500mg twice daily",
    familyHistory: "Not provided",
    other: "Walking has improved",
    aiSummary:
      "78-year-old patient on follow-up reporting partial improvement in knee pain since previous consultation. New complaint of occasional morning giddiness. Known diabetes and hypertension.",
    followUp: {
      improved: "Partially improved",
      previousSymptomsPresent: "Knee pain still present but reduced",
      newSymptoms: "Occasional giddiness in the morning",
      changes: "Started morning walks",
      concerns: "Worried about giddiness while walking",
    },
    notes: [
      {
        id: "n2",
        author: "Dr. Ravi Kumar",
        text: "Reviewed follow-up. Please visit OPD for blood pressure check before consultation.",
        createdAt: "2026-09-05T08:16:00.000Z",
        kind: "note",
      },
    ],
  },
  {
    id: "c4",
    caseId: "CS-2026-0117",
    profileId: "p3",
    hospitalId: "h2",
    doctorId: "d4",
    type: "emergency",
    status: "submitted",
    language: "en",
    createdAt: "2026-09-06T18:02:00.000Z",
    chiefComplaint: "Severe chest discomfort and breathlessness",
    duration: "1 hour",
    symptoms: "Chest discomfort, breathlessness, sweating",
    severity: "Severe",
    pastHistory: "Not provided",
    allergies: "Not provided",
    medications: "Not provided",
    familyHistory: "Not provided",
    other: "Patient advised to reach emergency department immediately",
    aiSummary:
      "EMERGENCY ALERT: 35-year-old patient reporting severe chest discomfort with breathlessness and sweating for one hour. Flagged as high priority for immediate attention.",
    notes: [],
  },
  {
    id: "c5",
    caseId: "CS-2026-0118",
    profileId: "p4",
    hospitalId: "h1",
    doctorId: "d2",
    type: "new",
    status: "consultation-pending",
    language: "hi",
    createdAt: "2026-09-06T04:25:00.000Z",
    reviewedAt: "2026-09-06T06:00:00.000Z",
    chiefComplaint: "Loose motions",
    duration: "2 days",
    symptoms: "Loose motions, mild fever, low energy",
    severity: "Moderate",
    pastHistory: "None",
    allergies: "None known",
    medications: "ORS given at home",
    familyHistory: "Not provided",
    other: "Ate outside food two days ago",
    aiSummary:
      "7-year-old child with loose motions for two days with mild fever and reduced energy. ORS administered at home. History of outside food intake.",
    notes: [],
  },
];
