import { createFileRoute, Link } from "@tanstack/react-router";
import { AppShell, PageHeader, useRequireRole } from "@/components/app-shell";
import { PATIENT_NAV } from "@/components/patient-nav";
import { ConsultationProgress, StatusBadge, TypeBadge } from "@/components/status-badge";
import { NoDiagnosisNotice } from "@/components/brand";
import { Button } from "@/components/ui/button";
import { useStore, ageFromDob } from "@/lib/store";

export const Route = createFileRoute("/patient/case/summary")({
  validateSearch: (search: Record<string, unknown>) => ({
    case: typeof search["case"] === "string" ? (search["case"] as string) : "",
  }),
  head: () => ({
    meta: [
      { title: "Case Summary — AyuSetu" },
      {
        name: "description",
        content:
          "Your submitted case summary with structured details and a clearly labelled AI summary for your doctor.",
      },
      { property: "og:title", content: "Case Summary — AyuSetu" },
      {
        property: "og:description",
        content: "Structured case details prepared for your doctor's review.",
      },
    ],
  }),
  component: CaseSummaryPage,
});

function CaseSummaryPage() {
  const account = useRequireRole("patient");
  const { case: caseParam } = Route.useSearch();
  const { cases, activeProfile, caseById, doctorById, hospitalById, profileById } =
    useStore();

  if (!account) return null;

  const record =
    (caseParam ? caseById(caseParam) : undefined) ??
    cases.find((c) => c.profileId === activeProfile?.id);

  if (!record) {
    return (
      <AppShell role="patient" nav={PATIENT_NAV}>
        <PageHeader title="Case Summary" />
        <p className="text-sm text-muted-foreground">No case found yet.</p>
        <Button asChild className="mt-4">
          <Link to="/patient/case/new">Start New Case</Link>
        </Button>
      </AppShell>
    );
  }

  const profile = profileById(record.profileId);
  const doctor = doctorById(record.doctorId);
  const hospital = hospitalById(record.hospitalId);

  return (
    <AppShell role="patient" nav={PATIENT_NAV}>
      <PageHeader
        title="Case submitted successfully."
        description="Your doctor will review this before your in-person consultation."
        action={
          <Button asChild variant="outline">
            <Link to="/patient/dashboard">Back to dashboard</Link>
          </Button>
        }
      />

      <div className="grid gap-6 lg:grid-cols-[1fr_320px]">
        <div className="space-y-6">
          <section className="surface-card p-6">
            <div className="flex flex-wrap items-center gap-3">
              <h2 className="text-lg font-semibold text-foreground">
                Patient Case Summary
              </h2>
              <TypeBadge type={record.type} />
              <StatusBadge status={record.status} />
            </div>
            <dl className="mt-4 grid gap-4 sm:grid-cols-2">
              <Item label="Patient" value={`${profile?.name} · ${profile?.patientId}`} />
              <Item
                label="Age / Gender"
                value={`${profile ? ageFromDob(profile.dob) : "—"} years · ${profile?.gender}`}
              />
              <Item label="Chief Complaint" value={record.chiefComplaint} />
              <Item label="Duration" value={record.duration} />
              <Item label="Symptoms" value={record.symptoms} />
              <Item label="Severity" value={record.severity} />
              <Item label="Medical History" value={record.pastHistory} />
              <Item label="Allergies" value={record.allergies} />
              <Item label="Current Medications" value={record.medications} />
              <Item label="Family History" value={record.familyHistory} />
              <Item label="Other Relevant Information" value={record.other} />
            </dl>
          </section>

          <section className="surface-card border-accent/30 p-6">
            <p className="text-xs font-semibold uppercase tracking-wide text-accent-foreground">
              AI Summary — generated by AyuSetu, requires doctor verification
            </p>
            <p className="mt-2 text-base leading-relaxed text-foreground">
              {record.aiSummary}
            </p>
          </section>

          <section className="surface-card p-6">
            <h2 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground">
              Consultation status
            </h2>
            <div className="mt-4">
              <ConsultationProgress status={record.status} />
            </div>
            {record.status !== "submitted" ? (
              <p className="mt-4 rounded-xl bg-accent-soft px-4 py-3 text-sm text-foreground">
                Your case has been reviewed by {doctor?.name}. Please visit the
                hospital for your consultation.
              </p>
            ) : null}
          </section>
        </div>

        <aside className="space-y-6">
          <section className="surface-card p-6">
            <h2 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground">
              Submission
            </h2>
            <dl className="mt-3 space-y-3 text-sm">
              <Item label="Case ID" value={record.caseId} />
              <Item label="Patient" value={profile?.name ?? "—"} />
              <Item label="Hospital" value={hospital?.name ?? "—"} />
              <Item label="Preferred Doctor" value={doctor?.name ?? "—"} />
              <Item
                label="Submitted"
                value={new Date(record.createdAt).toLocaleString("en-IN")}
              />
            </dl>
          </section>
          <NoDiagnosisNotice />
        </aside>
      </div>
    </AppShell>
  );
}

function Item({ label, value }: { label: string; value?: string }) {
  return (
    <div>
      <dt className="text-xs uppercase tracking-wide text-muted-foreground">
        {label}
      </dt>
      <dd className="mt-1 text-sm font-medium leading-relaxed text-foreground">
        {value?.trim() ? value : "Not provided"}
      </dd>
    </div>
  );
}
